# Generated by Django 3.1.13 on 2021-09-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(db_index=True, unique=True, verbose_name='original full url')),
                ('short_url', models.URLField(null=True, unique=True, verbose_name='shortened relative url')),
            ],
        ),
    ]
